### ISSUE TITLE
no module named parse

### ISSUE THREAD

**Issue by missingpuzzle233** [adamcw/autotune#3]
![44](https://user-images.githubusercontent.com/66463338/93415638-8ff35480-f8d6-11ea-9ff6-1966187fa728.png)

**Comment by missingpuzzle233** [comment]
when python run.py i got this error
this problem maybe caused by parse.py in 'processruns' floder:
`import parse
# Parser for the data lines of the output file
DEFAULT_PARSER = parse.compile(
    ">>> {time:g} {} {t:d} {} Last: {lastx:d} {lastz:d} {} Checks: {xchecks:d} {zchecks:d} {} Changes: {xchanges:d} {zchanges:d}")

# Parser for the option flags of the output file
DEFAULT_OPT_PARSER = parse.compile(
    "{opt} = {val}")
`

**Comment by adamcw** [comment]
Please read instructions in README.md inside /process/ folder. It has instructions to install the python dependencies to run this code.
